//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMS_WebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartTable
    {
        public System.DateTime DateOfItemAdded { get; set; }
        public int Quantity { get; set; }
        public string ProductID { get; set; }
        public string CustomerID { get; set; }
        public int CartID { get; set; }
    
        public virtual CustomerTable CustomerTable { get; set; }
        public virtual ProductTable ProductTable { get; set; }
    }
}
