//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMS_WebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderTable()
        {
            this.OrderProductLineTables = new HashSet<OrderProductLineTable>();
        }
    
        public string OrderID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public bool Status { get; set; }
        public int NetAmount { get; set; }
        public string CustomerID { get; set; }
    
        public virtual CustomerTable CustomerTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProductLineTable> OrderProductLineTables { get; set; }
    }
}
