//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMS_WebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProductLineTable
    {
        public int Quatity { get; set; }
        public int Rate { get; set; }
        public int GrossAmount { get; set; }
        public int DiscountAmount { get; set; }
        public int Disccount_ { get; set; }
        public int TaxAmount { get; set; }
        public int Tax_ { get; set; }
        public string OrderID { get; set; }
        public string ProductID { get; set; }
        public string OrderProductLineID { get; set; }
    
        public virtual ProductTable ProductTable { get; set; }
        public virtual OrderTable OrderTable { get; set; }
    }
}
