//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORMS_WebService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductTable()
        {
            this.CartTables = new HashSet<CartTable>();
            this.OrderProductLineTables = new HashSet<OrderProductLineTable>();
        }
    
        public string ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Prize { get; set; }
        public Nullable<int> ProductQuantity { get; set; }
        public string Image { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> Tax { get; set; }
        public Nullable<int> Discount { get; set; }
        public string CatagoryID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartTable> CartTables { get; set; }
        public virtual CatagoryTable CatagoryTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProductLineTable> OrderProductLineTables { get; set; }
    }
}
